//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ModeloDatos.ORM
{

    [Persistent(@"detalle_factura")]
    public partial class DetalleFactura : XPLiteObject
    {
        int fId;
        [Key(true)]
        [Persistent(@"id")]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fDescripcion;
        [Size(255)]
        [Persistent(@"descripcion")]
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        int fCantidadPedida;
        [Persistent(@"cantidad_pedida")]
        public int CantidadPedida
        {
            get { return fCantidadPedida; }
            set { SetPropertyValue<int>(nameof(CantidadPedida), ref fCantidadPedida, value); }
        }
        double fPrecioTotal;
        [Persistent(@"precio_total")]
        public double PrecioTotal
        {
            get { return fPrecioTotal; }
            set { SetPropertyValue<double>(nameof(PrecioTotal), ref fPrecioTotal, value); }
        }
        Factura fFacturaId;
        [Persistent(@"factura_id")]
        [Association(@"DetalleFacturaReferencesFactura")]
        public Factura FacturaId
        {
            get { return fFacturaId; }
            set { SetPropertyValue<Factura>(nameof(FacturaId), ref fFacturaId, value); }
        }
        Producto fProductoId;
        [Persistent(@"producto_id")]
        [Association(@"DetalleFacturaReferencesProducto")]
        public Producto ProductoId
        {
            get { return fProductoId; }
            set { SetPropertyValue<Producto>(nameof(ProductoId), ref fProductoId, value); }
        }
    }

}
