//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ModeloDatos.ORM
{

    [Persistent(@"empresa_telefonica")]
    public partial class EmpresaTelefonica : XPLiteObject
    {
        int fId;
        [Key(true)]
        [Persistent(@"id")]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fNombre;
        [Size(45)]
        [Persistent(@"nombre")]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fPrefijos;
        [Size(500)]
        [Persistent(@"prefijos")]
        public string Prefijos
        {
            get { return fPrefijos; }
            set { SetPropertyValue<string>(nameof(Prefijos), ref fPrefijos, value); }
        }
        [Association(@"TelefonoReferencesEmpresaTelefonica")]
        public XPCollection<Telefono> Telefonoes { get { return GetCollection<Telefono>(nameof(Telefonoes)); } }
    }

}
