//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ModeloDatos.ORM
{

    [Persistent(@"factura")]
    public partial class Factura : XPLiteObject
    {
        int fId;
        [Key(true)]
        [Persistent(@"id")]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fNumero;
        [Size(45)]
        [Persistent(@"numero")]
        public string Numero
        {
            get { return fNumero; }
            set { SetPropertyValue<string>(nameof(Numero), ref fNumero, value); }
        }
        DateTime fFecha;
        [Persistent(@"fecha")]
        public DateTime Fecha
        {
            get { return fFecha; }
            set { SetPropertyValue<DateTime>(nameof(Fecha), ref fFecha, value); }
        }
        double fTotal;
        [Persistent(@"total")]
        public double Total
        {
            get { return fTotal; }
            set { SetPropertyValue<double>(nameof(Total), ref fTotal, value); }
        }
        Cliente fClienteId;
        [Persistent(@"cliente_id")]
        [Association(@"FacturaReferencesCliente")]
        public Cliente ClienteId
        {
            get { return fClienteId; }
            set { SetPropertyValue<Cliente>(nameof(ClienteId), ref fClienteId, value); }
        }
        [Association(@"DetalleFacturaReferencesFactura")]
        public XPCollection<DetalleFactura> DetalleFacturas { get { return GetCollection<DetalleFactura>(nameof(DetalleFacturas)); } }
    }

}
