//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ModeloDatos.ORM
{

    [Persistent(@"municipio")]
    public partial class Municipio : XPLiteObject
    {
        int fId;
        [Key(true)]
        [Persistent(@"id")]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fNombre;
        [Size(45)]
        [Persistent(@"nombre")]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        Departamento fDepartamentoId;
        [Persistent(@"departamento_id")]
        [Association(@"MunicipioReferencesDepartamento")]
        public Departamento DepartamentoId
        {
            get { return fDepartamentoId; }
            set { SetPropertyValue<Departamento>(nameof(DepartamentoId), ref fDepartamentoId, value); }
        }
        [Association(@"ClienteReferencesMunicipio")]
        public XPCollection<Cliente> Clientes { get { return GetCollection<Cliente>(nameof(Clientes)); } }
    }

}
