//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ModeloDatos.ORM
{

    [Persistent(@"producto")]
    public partial class Producto : XPLiteObject
    {
        int fId;
        [Key]
        [Persistent(@"id")]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fNombre;
        [Size(255)]
        [Persistent(@"nombre")]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fDescripcion;
        [Size(255)]
        [Persistent(@"descripcion")]
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        string fColor;
        [Size(45)]
        [Persistent(@"color")]
        public string Color
        {
            get { return fColor; }
            set { SetPropertyValue<string>(nameof(Color), ref fColor, value); }
        }
        decimal fExistencias;
        [Persistent(@"existencias")]
        public decimal Existencias
        {
            get { return fExistencias; }
            set { SetPropertyValue<decimal>(nameof(Existencias), ref fExistencias, value); }
        }
        decimal fCosto;
        [Persistent(@"costo")]
        public decimal Costo
        {
            get { return fCosto; }
            set { SetPropertyValue<decimal>(nameof(Costo), ref fCosto, value); }
        }
        decimal fPrecioVenta;
        [Persistent(@"precio_venta")]
        public decimal PrecioVenta
        {
            get { return fPrecioVenta; }
            set { SetPropertyValue<decimal>(nameof(PrecioVenta), ref fPrecioVenta, value); }
        }
        Marca fMarcaId;
        [Persistent(@"marca_id")]
        [Association(@"ProductoReferencesMarca")]
        public Marca MarcaId
        {
            get { return fMarcaId; }
            set { SetPropertyValue<Marca>(nameof(MarcaId), ref fMarcaId, value); }
        }
        [Association(@"DetalleFacturaReferencesProducto")]
        public XPCollection<DetalleFactura> DetalleFacturas { get { return GetCollection<DetalleFactura>(nameof(DetalleFacturas)); } }
    }

}
