//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace ModeloDatos.ORM
{

    [Persistent(@"telefono")]
    public partial class Telefono : XPLiteObject
    {
        int fId;
        [Key]
        [Persistent(@"id")]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fNumero;
        [Size(50)]
        [Persistent(@"numero")]
        public string Numero
        {
            get { return fNumero; }
            set { SetPropertyValue<string>(nameof(Numero), ref fNumero, value); }
        }
        Cliente fClienteId;
        [Persistent(@"cliente_id")]
        [Association(@"TelefonoReferencesCliente")]
        public Cliente ClienteId
        {
            get { return fClienteId; }
            set { SetPropertyValue<Cliente>(nameof(ClienteId), ref fClienteId, value); }
        }
        EmpresaTelefonica fEmpresaTelefonicaId;
        [Persistent(@"empresa_telefonica_id")]
        [Association(@"TelefonoReferencesEmpresaTelefonica")]
        public EmpresaTelefonica EmpresaTelefonicaId
        {
            get { return fEmpresaTelefonicaId; }
            set { SetPropertyValue<EmpresaTelefonica>(nameof(EmpresaTelefonicaId), ref fEmpresaTelefonicaId, value); }
        }
    }

}
