//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication4.sisstemadelibreria
{

    [Persistent(@"cliente")]
    public partial class Cliente : XPLiteObject
    {
        int fidCliente;
        [Key(true)]
        public int idCliente
        {
            get { return fidCliente; }
            set { SetPropertyValue<int>(nameof(idCliente), ref fidCliente, value); }
        }
        string fCedula;
        [Size(25)]
        public string Cedula
        {
            get { return fCedula; }
            set { SetPropertyValue<string>(nameof(Cedula), ref fCedula, value); }
        }
        string fNombre;
        [Size(45)]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fApellido;
        [Size(45)]
        public string Apellido
        {
            get { return fApellido; }
            set { SetPropertyValue<string>(nameof(Apellido), ref fApellido, value); }
        }
        string fDireccion;
        [Size(45)]
        public string Direccion
        {
            get { return fDireccion; }
            set { SetPropertyValue<string>(nameof(Direccion), ref fDireccion, value); }
        }
        string fEmail;
        [Size(45)]
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        Municipio fMunicipio_idMunicipio;
        [Association(@"ClienteReferencesMunicipio")]
        public Municipio Municipio_idMunicipio
        {
            get { return fMunicipio_idMunicipio; }
            set { SetPropertyValue<Municipio>(nameof(Municipio_idMunicipio), ref fMunicipio_idMunicipio, value); }
        }
        [Association(@"FacturaReferencesCliente")]
        public XPCollection<Factura> Facturas { get { return GetCollection<Factura>(nameof(Facturas)); } }
        [Association(@"TelefonoReferencesCliente")]
        public XPCollection<Telefono> Telefonoes { get { return GetCollection<Telefono>(nameof(Telefonoes)); } }
    }

}
