//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication4.sisstemadelibreria
{

    [Persistent(@"detalladefactura")]
    public partial class Detalladefactura : XPLiteObject
    {
        int fidDetalladefactura;
        [Key(true)]
        public int idDetalladefactura
        {
            get { return fidDetalladefactura; }
            set { SetPropertyValue<int>(nameof(idDetalladefactura), ref fidDetalladefactura, value); }
        }
        string fDetalladefacturacol;
        [Size(45)]
        public string Detalladefacturacol
        {
            get { return fDetalladefacturacol; }
            set { SetPropertyValue<string>(nameof(Detalladefacturacol), ref fDetalladefacturacol, value); }
        }
        int fCantidadpedida;
        public int Cantidadpedida
        {
            get { return fCantidadpedida; }
            set { SetPropertyValue<int>(nameof(Cantidadpedida), ref fCantidadpedida, value); }
        }
        double fPreciototal;
        public double Preciototal
        {
            get { return fPreciototal; }
            set { SetPropertyValue<double>(nameof(Preciototal), ref fPreciototal, value); }
        }
        Factura fFactura_idFactura;
        [Association(@"DetalladefacturaReferencesFactura")]
        public Factura Factura_idFactura
        {
            get { return fFactura_idFactura; }
            set { SetPropertyValue<Factura>(nameof(Factura_idFactura), ref fFactura_idFactura, value); }
        }
        Producto fProducto_idProducto;
        [Association(@"DetalladefacturaReferencesProducto")]
        public Producto Producto_idProducto
        {
            get { return fProducto_idProducto; }
            set { SetPropertyValue<Producto>(nameof(Producto_idProducto), ref fProducto_idProducto, value); }
        }
    }

}
