//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication4.sisstemadelibreria
{

    [Persistent(@"empresa_telefonica")]
    public partial class Empresa_telefonica : XPLiteObject
    {
        int fidEmpresa_telefonica;
        [Key(true)]
        public int idEmpresa_telefonica
        {
            get { return fidEmpresa_telefonica; }
            set { SetPropertyValue<int>(nameof(idEmpresa_telefonica), ref fidEmpresa_telefonica, value); }
        }
        string fEmpresa;
        [Size(45)]
        public string Empresa
        {
            get { return fEmpresa; }
            set { SetPropertyValue<string>(nameof(Empresa), ref fEmpresa, value); }
        }
        string fPrefijos;
        [Size(500)]
        public string Prefijos
        {
            get { return fPrefijos; }
            set { SetPropertyValue<string>(nameof(Prefijos), ref fPrefijos, value); }
        }
        [Association(@"TelefonoReferencesEmpresa_telefonica")]
        public XPCollection<Telefono> Telefonoes { get { return GetCollection<Telefono>(nameof(Telefonoes)); } }
    }

}
