//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication4.sisstemadelibreria
{

    [Persistent(@"factura")]
    public partial class Factura : XPLiteObject
    {
        int fidFactura;
        [Key(true)]
        public int idFactura
        {
            get { return fidFactura; }
            set { SetPropertyValue<int>(nameof(idFactura), ref fidFactura, value); }
        }
        string fNoFactura;
        [Size(45)]
        public string NoFactura
        {
            get { return fNoFactura; }
            set { SetPropertyValue<string>(nameof(NoFactura), ref fNoFactura, value); }
        }
        DateTime fFecha;
        public DateTime Fecha
        {
            get { return fFecha; }
            set { SetPropertyValue<DateTime>(nameof(Fecha), ref fFecha, value); }
        }
        double fTotaldefactura;
        public double Totaldefactura
        {
            get { return fTotaldefactura; }
            set { SetPropertyValue<double>(nameof(Totaldefactura), ref fTotaldefactura, value); }
        }
        Cliente fCliente_idCliente;
        [Association(@"FacturaReferencesCliente")]
        public Cliente Cliente_idCliente
        {
            get { return fCliente_idCliente; }
            set { SetPropertyValue<Cliente>(nameof(Cliente_idCliente), ref fCliente_idCliente, value); }
        }
        [Association(@"DetalladefacturaReferencesFactura")]
        public XPCollection<Detalladefactura> Detalladefacturas { get { return GetCollection<Detalladefactura>(nameof(Detalladefacturas)); } }
    }

}
