//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication4.sisstemadelibreria
{

    [Persistent(@"marca")]
    public partial class Marca : XPLiteObject
    {
        int fidMarca;
        [Key]
        public int idMarca
        {
            get { return fidMarca; }
            set { SetPropertyValue<int>(nameof(idMarca), ref fidMarca, value); }
        }
        string fmarca;
        [Size(45)]
        public string marca
        {
            get { return fmarca; }
            set { SetPropertyValue<string>(nameof(marca), ref fmarca, value); }
        }
        [Association(@"ProductoReferencesMarca")]
        public XPCollection<Producto> Productoes { get { return GetCollection<Producto>(nameof(Productoes)); } }
    }

}
