//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication4.sisstemadelibreria
{

    [Persistent(@"municipio")]
    public partial class Municipio : XPLiteObject
    {
        int fidMunicipio;
        [Key]
        public int idMunicipio
        {
            get { return fidMunicipio; }
            set { SetPropertyValue<int>(nameof(idMunicipio), ref fidMunicipio, value); }
        }
        string fMunicipio1;
        [Size(45)]
        [Persistent(@"Municipio")]
        public string Municipio1
        {
            get { return fMunicipio1; }
            set { SetPropertyValue<string>(nameof(Municipio1), ref fMunicipio1, value); }
        }
        Departamento fDepartamento_idDepartamento;
        [Association(@"MunicipioReferencesDepartamento")]
        public Departamento Departamento_idDepartamento
        {
            get { return fDepartamento_idDepartamento; }
            set { SetPropertyValue<Departamento>(nameof(Departamento_idDepartamento), ref fDepartamento_idDepartamento, value); }
        }
        [Association(@"ClienteReferencesMunicipio")]
        public XPCollection<Cliente> Clientes { get { return GetCollection<Cliente>(nameof(Clientes)); } }
    }

}
