//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication4.sisstemadelibreria
{

    [Persistent(@"permisos")]
    public partial class Permisos : XPLiteObject
    {
        int fidPermisos;
        [Key]
        public int idPermisos
        {
            get { return fidPermisos; }
            set { SetPropertyValue<int>(nameof(idPermisos), ref fidPermisos, value); }
        }
        string fPermisoscol;
        [Size(45)]
        public string Permisoscol
        {
            get { return fPermisoscol; }
            set { SetPropertyValue<string>(nameof(Permisoscol), ref fPermisoscol, value); }
        }
    }

}
