//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication4.sisstemadelibreria
{

    [Persistent(@"producto")]
    public partial class Producto : XPLiteObject
    {
        int fidProducto;
        [Key]
        public int idProducto
        {
            get { return fidProducto; }
            set { SetPropertyValue<int>(nameof(idProducto), ref fidProducto, value); }
        }
        string fProductoco;
        [Size(45)]
        public string Productoco
        {
            get { return fProductoco; }
            set { SetPropertyValue<string>(nameof(Productoco), ref fProductoco, value); }
        }
        string fDescripcion;
        [Size(45)]
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        string fProductocol;
        [Size(45)]
        public string Productocol
        {
            get { return fProductocol; }
            set { SetPropertyValue<string>(nameof(Productocol), ref fProductocol, value); }
        }
        string fColor;
        [Size(45)]
        public string Color
        {
            get { return fColor; }
            set { SetPropertyValue<string>(nameof(Color), ref fColor, value); }
        }
        string fUnidadenexistencia;
        [Size(45)]
        public string Unidadenexistencia
        {
            get { return fUnidadenexistencia; }
            set { SetPropertyValue<string>(nameof(Unidadenexistencia), ref fUnidadenexistencia, value); }
        }
        string fPreciodecosto;
        [Size(45)]
        public string Preciodecosto
        {
            get { return fPreciodecosto; }
            set { SetPropertyValue<string>(nameof(Preciodecosto), ref fPreciodecosto, value); }
        }
        string fPreciodeventa;
        [Size(45)]
        public string Preciodeventa
        {
            get { return fPreciodeventa; }
            set { SetPropertyValue<string>(nameof(Preciodeventa), ref fPreciodeventa, value); }
        }
        Marca fMarca_idMarca;
        [Association(@"ProductoReferencesMarca")]
        public Marca Marca_idMarca
        {
            get { return fMarca_idMarca; }
            set { SetPropertyValue<Marca>(nameof(Marca_idMarca), ref fMarca_idMarca, value); }
        }
        [Association(@"DetalladefacturaReferencesProducto")]
        public XPCollection<Detalladefactura> Detalladefacturas { get { return GetCollection<Detalladefactura>(nameof(Detalladefacturas)); } }
    }

}
