//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication4.sisstemadelibreria
{

    [Persistent(@"producto_has_proveedor")]
    public partial class Producto_has_proveedor : XPLiteObject
    {
        public struct CompoundKey1Struct
        {
            [Persistent("Producto_idProducto")]
            public int Producto_idProducto { get; set; }
            [Persistent("Proveedor_idProveedor")]
            public int Proveedor_idProveedor { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
