//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication4.sisstemadelibreria
{

    [Persistent(@"proveedor_has_municipio")]
    public partial class Proveedor_has_municipio : XPLiteObject
    {
        public struct CompoundKey1Struct
        {
            [Persistent("Proveedor_idProveedor")]
            public int Proveedor_idProveedor { get; set; }
            [Persistent("Municipio_idMunicipio")]
            public int Municipio_idMunicipio { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
