//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication4.sisstemadelibreria
{

    [Persistent(@"proveedor")]
    public partial class Proveedor : XPLiteObject
    {
        int fidProveedor;
        [Key]
        public int idProveedor
        {
            get { return fidProveedor; }
            set { SetPropertyValue<int>(nameof(idProveedor), ref fidProveedor, value); }
        }
        string fCedula;
        [Size(45)]
        public string Cedula
        {
            get { return fCedula; }
            set { SetPropertyValue<string>(nameof(Cedula), ref fCedula, value); }
        }
        string fProveedor1;
        [Size(80)]
        [Persistent(@"Proveedor")]
        public string Proveedor1
        {
            get { return fProveedor1; }
            set { SetPropertyValue<string>(nameof(Proveedor1), ref fProveedor1, value); }
        }
        string fDireccion;
        [Size(45)]
        public string Direccion
        {
            get { return fDireccion; }
            set { SetPropertyValue<string>(nameof(Direccion), ref fDireccion, value); }
        }
        string fRepresentante;
        [Size(45)]
        public string Representante
        {
            get { return fRepresentante; }
            set { SetPropertyValue<string>(nameof(Representante), ref fRepresentante, value); }
        }
        string fEmail;
        [Size(45)]
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        [Association(@"TelefonoReferencesProveedor")]
        public XPCollection<Telefono> Telefonoes { get { return GetCollection<Telefono>(nameof(Telefonoes)); } }
    }

}
