//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication4.sisstemadelibreria
{

    [Persistent(@"role_has_permisos")]
    public partial class Role_has_permisos : XPLiteObject
    {
        public struct CompoundKey1Struct
        {
            [Persistent("idrole")]
            public int idrole { get; set; }
            [Persistent("idPermisos")]
            public int idPermisos { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
