//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication4.sisstemadelibreria
{

    [Persistent(@"role")]
    public partial class Role : XPLiteObject
    {
        int fidrole;
        [Key]
        public int idrole
        {
            get { return fidrole; }
            set { SetPropertyValue<int>(nameof(idrole), ref fidrole, value); }
        }
        string fName;
        [Size(45)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        Usuario fidUsuario;
        [Association(@"RoleReferencesUsuario")]
        public Usuario idUsuario
        {
            get { return fidUsuario; }
            set { SetPropertyValue<Usuario>(nameof(idUsuario), ref fidUsuario, value); }
        }
    }

}
