//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication4.sisstemadelibreria
{

    [Persistent(@"telefono")]
    public partial class Telefono : XPLiteObject
    {
        int fidTelefono;
        [Key]
        public int idTelefono
        {
            get { return fidTelefono; }
            set { SetPropertyValue<int>(nameof(idTelefono), ref fidTelefono, value); }
        }
        string fTelefono1;
        [Size(45)]
        [Persistent(@"Telefono")]
        public string Telefono1
        {
            get { return fTelefono1; }
            set { SetPropertyValue<string>(nameof(Telefono1), ref fTelefono1, value); }
        }
        Cliente fCliente_idCliente;
        [Association(@"TelefonoReferencesCliente")]
        public Cliente Cliente_idCliente
        {
            get { return fCliente_idCliente; }
            set { SetPropertyValue<Cliente>(nameof(Cliente_idCliente), ref fCliente_idCliente, value); }
        }
        Empresa_telefonica fidEmpresa_telefonica;
        [Association(@"TelefonoReferencesEmpresa_telefonica")]
        public Empresa_telefonica idEmpresa_telefonica
        {
            get { return fidEmpresa_telefonica; }
            set { SetPropertyValue<Empresa_telefonica>(nameof(idEmpresa_telefonica), ref fidEmpresa_telefonica, value); }
        }
        Proveedor fProveedor_idProveedor;
        [Association(@"TelefonoReferencesProveedor")]
        public Proveedor Proveedor_idProveedor
        {
            get { return fProveedor_idProveedor; }
            set { SetPropertyValue<Proveedor>(nameof(Proveedor_idProveedor), ref fProveedor_idProveedor, value); }
        }
    }

}
