//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication4.sisstemadelibreria
{

    [Persistent(@"usuario")]
    public partial class Usuario : XPLiteObject
    {
        int fidUsuario;
        [Key(true)]
        public int idUsuario
        {
            get { return fidUsuario; }
            set { SetPropertyValue<int>(nameof(idUsuario), ref fidUsuario, value); }
        }
        string fUsuario1;
        [Size(45)]
        [Persistent(@"Usuario")]
        public string Usuario1
        {
            get { return fUsuario1; }
            set { SetPropertyValue<string>(nameof(Usuario1), ref fUsuario1, value); }
        }
        string fClave;
        [Size(45)]
        public string Clave
        {
            get { return fClave; }
            set { SetPropertyValue<string>(nameof(Clave), ref fClave, value); }
        }
        [Association(@"RoleReferencesUsuario")]
        public XPCollection<Role> Roles { get { return GetCollection<Role>(nameof(Roles)); } }
    }

}
